export const COLLECTIONS = {
  USERS: 'users',
  DONATIONS: 'donations',
  BLOOD_REQUESTS: 'bloodRequests',
  BLOOD_INVENTORY: 'bloodInventory',
  CAMPAIGNS: 'campaigns',
  APPOINTMENTS: 'appointments',
  VOLUNTEERS: 'volunteers',
  PARTNERSHIPS: 'partnerships',
  NOTIFICATIONS: 'notifications',
  BADGES: 'badges',
  USER_BADGES: 'userBadges',
  VERIFICATION_REQUESTS: 'verificationRequests',
  ANALYTICS: 'analytics',
  AUDIT_LOGS: 'auditLogs',
  ERROR_LOGS: 'errorLogs',
  PUBLIC_DONORS: 'publicDonors',
  USER_STATS: 'userStats',
  DONATION_HISTORY: 'DonationHistory',
  DONOR_REQUESTS: 'donorRequests',
  DONOR_REQUEST_BATCHES: 'donorRequestBatches',
  PENDING_DONOR_REQUESTS: 'pendingDonorRequests',
  REFERRAL_TRACKING: 'ReferralTracking',
  IMPERSONATION_EVENTS: 'impersonationEvents',
  INVENTORY_ALERTS: 'inventoryAlerts',
  CONTACT_SUBMISSIONS: 'contactSubmissions',
  CONTACT_RATE_LIMITS: 'contactRateLimits',
  INVENTORY_TRANSFERS: 'inventoryTransfers',
  INVENTORY_RESERVATIONS: 'inventoryReservations',
  INVENTORY_TRANSACTIONS: 'inventoryTransactions',
  BLOODBANK_BRANCHES: 'bloodbankBranches',
  POINT_TRANSACTIONS: 'pointTransactions',
  DONATION_FEEDBACK: 'DonationFeedback',
} as const;

export type CollectionName = (typeof COLLECTIONS)[keyof typeof COLLECTIONS];
